/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AuthedRouteImport } from './routes/_authed'
import { Route as AuthedIndexRouteImport } from './routes/_authed/index'
import { Route as OfferDeclineRouteImport } from './routes/offer.decline'
import { Route as OfferAcceptRouteImport } from './routes/offer.accept'
import { Route as DisplayStoreIdRouteImport } from './routes/display.$storeId'
import { Route as AuthedUsersRouteImport } from './routes/_authed/users'
import { Route as AuthedStaffRouteImport } from './routes/_authed/staff'
import { Route as AuthedShiftsRouteImport } from './routes/_authed/shifts'
import { Route as AuthedSettingsRouteImport } from './routes/_authed/settings'
import { Route as AuthedReportsRouteImport } from './routes/_authed/reports'
import { Route as AuthedPunchRouteImport } from './routes/_authed/punch'
import { Route as AuthedPermissionsRouteImport } from './routes/_authed/permissions'
import { Route as AuthedAttendanceRouteImport } from './routes/_authed/attendance'
import { Route as AuthedBoardIndexRouteImport } from './routes/_authed/board.index'
import { Route as AuthedBoardAnnIdRouteImport } from './routes/_authed/board.$annId'

const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthedRoute = AuthedRouteImport.update({
  id: '/_authed',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthedIndexRoute = AuthedIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthedRoute,
} as any)
const OfferDeclineRoute = OfferDeclineRouteImport.update({
  id: '/offer/decline',
  path: '/offer/decline',
  getParentRoute: () => rootRouteImport,
} as any)
const OfferAcceptRoute = OfferAcceptRouteImport.update({
  id: '/offer/accept',
  path: '/offer/accept',
  getParentRoute: () => rootRouteImport,
} as any)
const DisplayStoreIdRoute = DisplayStoreIdRouteImport.update({
  id: '/display/$storeId',
  path: '/display/$storeId',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthedUsersRoute = AuthedUsersRouteImport.update({
  id: '/users',
  path: '/users',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedStaffRoute = AuthedStaffRouteImport.update({
  id: '/staff',
  path: '/staff',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedShiftsRoute = AuthedShiftsRouteImport.update({
  id: '/shifts',
  path: '/shifts',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedSettingsRoute = AuthedSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedReportsRoute = AuthedReportsRouteImport.update({
  id: '/reports',
  path: '/reports',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedPunchRoute = AuthedPunchRouteImport.update({
  id: '/punch',
  path: '/punch',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedPermissionsRoute = AuthedPermissionsRouteImport.update({
  id: '/permissions',
  path: '/permissions',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedAttendanceRoute = AuthedAttendanceRouteImport.update({
  id: '/attendance',
  path: '/attendance',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedBoardIndexRoute = AuthedBoardIndexRouteImport.update({
  id: '/board/',
  path: '/board/',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedBoardAnnIdRoute = AuthedBoardAnnIdRouteImport.update({
  id: '/board/$annId',
  path: '/board/$annId',
  getParentRoute: () => AuthedRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof AuthedIndexRoute
  '/login': typeof LoginRoute
  '/attendance': typeof AuthedAttendanceRoute
  '/permissions': typeof AuthedPermissionsRoute
  '/punch': typeof AuthedPunchRoute
  '/reports': typeof AuthedReportsRoute
  '/settings': typeof AuthedSettingsRoute
  '/shifts': typeof AuthedShiftsRoute
  '/staff': typeof AuthedStaffRoute
  '/users': typeof AuthedUsersRoute
  '/display/$storeId': typeof DisplayStoreIdRoute
  '/offer/accept': typeof OfferAcceptRoute
  '/offer/decline': typeof OfferDeclineRoute
  '/board/$annId': typeof AuthedBoardAnnIdRoute
  '/board/': typeof AuthedBoardIndexRoute
}
export interface FileRoutesByTo {
  '/login': typeof LoginRoute
  '/attendance': typeof AuthedAttendanceRoute
  '/permissions': typeof AuthedPermissionsRoute
  '/punch': typeof AuthedPunchRoute
  '/reports': typeof AuthedReportsRoute
  '/settings': typeof AuthedSettingsRoute
  '/shifts': typeof AuthedShiftsRoute
  '/staff': typeof AuthedStaffRoute
  '/users': typeof AuthedUsersRoute
  '/display/$storeId': typeof DisplayStoreIdRoute
  '/offer/accept': typeof OfferAcceptRoute
  '/offer/decline': typeof OfferDeclineRoute
  '/': typeof AuthedIndexRoute
  '/board/$annId': typeof AuthedBoardAnnIdRoute
  '/board': typeof AuthedBoardIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_authed': typeof AuthedRouteWithChildren
  '/login': typeof LoginRoute
  '/_authed/attendance': typeof AuthedAttendanceRoute
  '/_authed/permissions': typeof AuthedPermissionsRoute
  '/_authed/punch': typeof AuthedPunchRoute
  '/_authed/reports': typeof AuthedReportsRoute
  '/_authed/settings': typeof AuthedSettingsRoute
  '/_authed/shifts': typeof AuthedShiftsRoute
  '/_authed/staff': typeof AuthedStaffRoute
  '/_authed/users': typeof AuthedUsersRoute
  '/display/$storeId': typeof DisplayStoreIdRoute
  '/offer/accept': typeof OfferAcceptRoute
  '/offer/decline': typeof OfferDeclineRoute
  '/_authed/': typeof AuthedIndexRoute
  '/_authed/board/$annId': typeof AuthedBoardAnnIdRoute
  '/_authed/board/': typeof AuthedBoardIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/attendance'
    | '/permissions'
    | '/punch'
    | '/reports'
    | '/settings'
    | '/shifts'
    | '/staff'
    | '/users'
    | '/display/$storeId'
    | '/offer/accept'
    | '/offer/decline'
    | '/board/$annId'
    | '/board/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/login'
    | '/attendance'
    | '/permissions'
    | '/punch'
    | '/reports'
    | '/settings'
    | '/shifts'
    | '/staff'
    | '/users'
    | '/display/$storeId'
    | '/offer/accept'
    | '/offer/decline'
    | '/'
    | '/board/$annId'
    | '/board'
  id:
    | '__root__'
    | '/_authed'
    | '/login'
    | '/_authed/attendance'
    | '/_authed/permissions'
    | '/_authed/punch'
    | '/_authed/reports'
    | '/_authed/settings'
    | '/_authed/shifts'
    | '/_authed/staff'
    | '/_authed/users'
    | '/display/$storeId'
    | '/offer/accept'
    | '/offer/decline'
    | '/_authed/'
    | '/_authed/board/$annId'
    | '/_authed/board/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AuthedRoute: typeof AuthedRouteWithChildren
  LoginRoute: typeof LoginRoute
  DisplayStoreIdRoute: typeof DisplayStoreIdRoute
  OfferAcceptRoute: typeof OfferAcceptRoute
  OfferDeclineRoute: typeof OfferDeclineRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authed': {
      id: '/_authed'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authed/': {
      id: '/_authed/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AuthedIndexRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/offer/decline': {
      id: '/offer/decline'
      path: '/offer/decline'
      fullPath: '/offer/decline'
      preLoaderRoute: typeof OfferDeclineRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/offer/accept': {
      id: '/offer/accept'
      path: '/offer/accept'
      fullPath: '/offer/accept'
      preLoaderRoute: typeof OfferAcceptRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/display/$storeId': {
      id: '/display/$storeId'
      path: '/display/$storeId'
      fullPath: '/display/$storeId'
      preLoaderRoute: typeof DisplayStoreIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authed/users': {
      id: '/_authed/users'
      path: '/users'
      fullPath: '/users'
      preLoaderRoute: typeof AuthedUsersRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/staff': {
      id: '/_authed/staff'
      path: '/staff'
      fullPath: '/staff'
      preLoaderRoute: typeof AuthedStaffRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/shifts': {
      id: '/_authed/shifts'
      path: '/shifts'
      fullPath: '/shifts'
      preLoaderRoute: typeof AuthedShiftsRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/settings': {
      id: '/_authed/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof AuthedSettingsRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/reports': {
      id: '/_authed/reports'
      path: '/reports'
      fullPath: '/reports'
      preLoaderRoute: typeof AuthedReportsRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/punch': {
      id: '/_authed/punch'
      path: '/punch'
      fullPath: '/punch'
      preLoaderRoute: typeof AuthedPunchRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/permissions': {
      id: '/_authed/permissions'
      path: '/permissions'
      fullPath: '/permissions'
      preLoaderRoute: typeof AuthedPermissionsRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/attendance': {
      id: '/_authed/attendance'
      path: '/attendance'
      fullPath: '/attendance'
      preLoaderRoute: typeof AuthedAttendanceRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/board/': {
      id: '/_authed/board/'
      path: '/board'
      fullPath: '/board/'
      preLoaderRoute: typeof AuthedBoardIndexRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/board/$annId': {
      id: '/_authed/board/$annId'
      path: '/board/$annId'
      fullPath: '/board/$annId'
      preLoaderRoute: typeof AuthedBoardAnnIdRouteImport
      parentRoute: typeof AuthedRoute
    }
  }
}

interface AuthedRouteChildren {
  AuthedAttendanceRoute: typeof AuthedAttendanceRoute
  AuthedPermissionsRoute: typeof AuthedPermissionsRoute
  AuthedPunchRoute: typeof AuthedPunchRoute
  AuthedReportsRoute: typeof AuthedReportsRoute
  AuthedSettingsRoute: typeof AuthedSettingsRoute
  AuthedShiftsRoute: typeof AuthedShiftsRoute
  AuthedStaffRoute: typeof AuthedStaffRoute
  AuthedUsersRoute: typeof AuthedUsersRoute
  AuthedIndexRoute: typeof AuthedIndexRoute
  AuthedBoardAnnIdRoute: typeof AuthedBoardAnnIdRoute
  AuthedBoardIndexRoute: typeof AuthedBoardIndexRoute
}

const AuthedRouteChildren: AuthedRouteChildren = {
  AuthedAttendanceRoute: AuthedAttendanceRoute,
  AuthedPermissionsRoute: AuthedPermissionsRoute,
  AuthedPunchRoute: AuthedPunchRoute,
  AuthedReportsRoute: AuthedReportsRoute,
  AuthedSettingsRoute: AuthedSettingsRoute,
  AuthedShiftsRoute: AuthedShiftsRoute,
  AuthedStaffRoute: AuthedStaffRoute,
  AuthedUsersRoute: AuthedUsersRoute,
  AuthedIndexRoute: AuthedIndexRoute,
  AuthedBoardAnnIdRoute: AuthedBoardAnnIdRoute,
  AuthedBoardIndexRoute: AuthedBoardIndexRoute,
}

const AuthedRouteWithChildren =
  AuthedRoute._addFileChildren(AuthedRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  AuthedRoute: AuthedRouteWithChildren,
  LoginRoute: LoginRoute,
  DisplayStoreIdRoute: DisplayStoreIdRoute,
  OfferAcceptRoute: OfferAcceptRoute,
  OfferDeclineRoute: OfferDeclineRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
